[package]
name = "bevycheck"
version = "0.1.0"
authors = ["Jakob Hellermann <hellermann@sipgate.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1.0"
proc-macro-error = "1.0"
bevy = { git = "https://github.com/bevyengine/bevy", default-features = false }

[dev-dependencies]
trybuild = "1.0"

# [[test]]
# name = "try"
# path = "tests/ui/test.rs"